# Generated by Django 4.1.5 on 2023-01-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email_address', models.CharField(max_length=50)),
                ('code_phone', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=150)),
                ('message', models.TextField(max_length=20000)),
                ('file', models.FileField(upload_to='media/contact/')),
            ],
            options={
                'verbose_name': 'Cantact',
            },
        ),
    ]
