# Generated by Django 4.1.5 on 2023-02-10 02:04

import app.contact.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0002_delete_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_uuid', models.UUIDField()),
                ('file', models.FileField(upload_to=app.contact.models.contact_directory_path)),
            ],
        ),
    ]
