# Generated by Django 4.1.5 on 2023-02-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='code_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contactform',
            name='email_address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contactform',
            name='message',
            field=models.TextField(blank=True, verbose_name='contenido'),
        ),
        migrations.AddField(
            model_name='contactform',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contactform',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
