# Generated by Django 4.1.5 on 2023-02-26 23:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contactform_code_phone_contactform_email_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='contact_uuid',
        ),
        migrations.AddField(
            model_name='contactform',
            name='contact_id',
            field=models.PositiveIntegerField(default=1, unique=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
