# Generated by Django 4.1.5 on 2023-03-03 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_remove_contactform_contact_uuid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'verbose_name': 'Cantact'},
        ),
    ]
