# Generated by Django 4.1.5 on 2023-03-04 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_contactform_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'ordering': ('-sended',)},
        ),
        migrations.AddField(
            model_name='contactform',
            name='sended',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
