# Generated by Django 4.1.5 on 2023-03-08 01:30

import app.contact.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_alter_contactform_options_contactform_sended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='file',
            field=models.FileField(blank=True, upload_to=app.contact.models.contact_directory_path),
        ),
    ]
