# Generated by Django 4.1.5 on 2023-03-12 15:27

import app.contact.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_alter_contactform_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=app.contact.models.contact_directory_path),
        ),
    ]
