# Generated by Django 4.1.5 on 2023-03-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0013_alter_contactform_options_contactform_sended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
