# Generated by Django 4.1.5 on 2023-03-13 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0014_alter_contactform_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={},
        ),
    ]
