# Generated by Django 4.1.5 on 2023-03-18 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0016_codephone_alter_contactform_code_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='file',
        ),
    ]
