# Generated by Django 4.1.5 on 2023-03-18 02:43

import app.contact.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0017_remove_contactform_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=app.contact.models.contact_directory_path),
        ),
    ]
