# Generated by Django 4.1.5 on 2023-03-18 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0018_contactform_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='Contact',
        ),
    ]
