# Generated by Django 4.1.5 on 2023-04-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0019_rename_contactform_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='sended',
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_address',
            field=models.CharField(max_length=50),
        ),
    ]
