# Generated by Django 4.1.5 on 2023-04-08 19:13

import app.contact.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0020_remove_contact_sended_alter_contact_email_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodePhone',
        ),
        migrations.AlterField(
            model_name='contact',
            name='file',
            field=models.FileField(null=True, upload_to=app.contact.models.contact_directory_path),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='contenido'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
