# Generated by Django 4.1.5 on 2023-04-23 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0021_delete_codephone_alter_contact_file_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contact',
            managers=[
            ],
        ),
    ]
