# Generated by Django 4.1.5 on 2023-04-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='blog_uuid',
            new_name='repository_uuid',
        ),
        migrations.AddField(
            model_name='repository',
            name='url',
            field=models.URLField(default='http://www.siprad.com'),
        ),
    ]
